### ISSUE TITLE
[RFC] Debugger design draft

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii-debug#33]
Here's debugger design we've planned together with @xepozz.

General idea is to separate data collection and data display. In Yii 2 it was not
split so design was not convenient for both APIs and displaying data from
multiple servers.

Collection goes to [yiisoft/yii-debug](https://github.com/yiisoft/yii-debug),
API goes to [yiisoft/yii-debug-api](https://github.com/yiisoft/yii-debug-api),
displaying goes to [yiisoft/yii-debug-viewer](https://github.com/yiisoft/yii-debug-viewer).

## Modules

Debugger is extendable via modules. Each module provides:

- One of multiple data collectors
- Debug viewer panel
- Debug toolbar panel (optionally)

Modules are distributed as packages named as `yii-debug-<name>`.

### Collecting data

Debug data collector is modular and is using multiple application requests:
`ApplicationStartup`, `ApplicationShutdown`, `BeforeRequest` and `AfterRequest`.

On `ApplicationStartup` each module may register its own listener for events
containing data it needs. When such event occurs, data is being collected.
On `AfterRequest` and `ApplicationShutdown` data is flushed and persisted.

As an alternative, on `ApplicationStartup` any initialization could be done and at `ApplicationShutdown` data could be collected directly from service without using events.

An interface for collector:

```php
interface DebugDataCollectorInterface
{
    public function startup(): void;
    public function shutdown(): void;
    public function flush(): array;
}
```

As an extra idea we may implement a decorator for DI container that would return service proxies that may record data.

### Data collected

Besides module-specific data, all modules write common information about the data
collected:

1. Date and time of occurence.
2. A set of tags such as "application ID" or "server".

The following collectors are planned:

- EventsCollector
- ReqeustCollector
- ResponseCollector
- LogCollector
- ViewsCollector
- RoutesCollector
- FrameworkInfoCollector
- ComposerCollector
- DIContainerCollector

### Storing data

Data persistence happens via an interface. Default implementation wites to files.
For the case of multiple servers storage should be switched to a shared one.

```php
interface DebugDataStoreInterface
{
    public function persist(DebugDataInterface $data): void;
    public function list();
    public function read(): DebugDataInterface;
}

interface DebugDataInterface
{
    public function get(string $key);
}
```

## Displaying data

Data collected during current request is displayed in a debug toolbar in form
of a very short summary. Previously collected data along with details could
be viewed via debug viewer.

Debug toolbar is implemented as middleware that adds extra HTML / JS code to
each page. For what to append it is querying all modules for an instance of
`DebugToolbarPanelInterface`:

```php
interface DebugToolbarPanelInterface
{
    public function render(): string;
}
```

Debug viewer panel is implemented as another interface:

```php
interface DebugViewerPanelInterface
{
    public static function name(): string;
    public function render(): string;
}
```

When debug viewer is getting a list of panels, it is querying `name()` from each
module. When rendering a panel, `render()` method is used.

There should be a view when all data collected is listed. There we should be able to filter by data tag.

## Implementation plan

- [x] Get feedback
- [x] Fix interfaces
- [x] Implement two collectors from the list
- [x] Implement file storage
- [x] Implement debug panel
- [x] Implement debug viewer
- [x] Get feedback
- [x] Fix whatever is not correct
- [x] Implement the rest of collectors

## References

- https://github.com/yiisoft/yii-debug/issues/28 - Multi server support for debug panel
- https://github.com/yiisoft/yii-debug/issues/27 - Export/Import results
- https://github.com/yiisoft/yii-debug/issues/26 - Separate debugging and showing results
- https://github.com/yiisoft/yii-debug/issues/25 - Standalone debug application
- https://github.com/yiisoft/yii-debug/issues/24 - Allow debugging console application

**Comment by roxblnfk** [comment]
> Debug toolbar is implemented as middleware that adds extra HTML / JS code to
> each page. For what to append it is querying all modules for an instance of
> `DebugToolbarPanelInterface`

I suggest a different way.
For debug make a separate API.
To access the API we can use a custom HTTP header with a session id or token.

The task for `DebugMiddleware`:
- first when `DebugMiddleware` receives debug headers (API token), it immediately redirects Request to debugger routing
- if no API token then registers a `DebugAsset` before rendering page. For non-html pages the `DebugAsset` will be ignored
- after rendering write the API token in the Response headers.

What we have:
- debugging ajax requests within a session
- we do not modify the response body
- injection debugger into any frontend

**Comment by samdark** [comment]
The idea is interesting.

```php
<?php
class DebugMiddleware implements MiddlewareInterface
{
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        // start collecting data (register handlers etc.)
        $response = $handler->handle($request);
        // stop collecting data, add headers w/ debug data ID to $response
        return $response;
    }
}
```

DebugAsset registers a JS that checks a header and inserts debug toolbar HTML as it was done in Yii 2.

> first when DebugMiddleware receives debug headers (API token), it immediately redirects Request to debugger routing

This part I don't understand. What's about the redirect? Why do we need to do it?

**Comment by roxblnfk** [comment]
> This part I don't understand. What's about the redirect? Why do we need to do it?

I do not mean HTTP-redirect. I mean clipping Pipeline of the Application.
In this case we do not collect data for debug, but return accumulated data.

**Comment by kamarton** [comment]
> Storing data

It is not clear to me how the debug data from multiple applications (console, api, frontend ...) and its separated requests (eg for the current session) how will be listed.

> To access the API we can use a custom HTTP header with a session id or token.

Sounds good. It also greatly facilitates the processing of cases where the yii3 API is used by an Android, SDK or other non-web application. Since the token not containing debug data does not pose any risk, it is possible to send the header to a third party in case of problems and to return it in case of problems.

> if no API token then registers a DebugAsset before rendering page. For non-html pages the DebugAsset will be ignored

It would also be useful to have an option where no debug toolbar is included in HTML and you can only view it in a completely separate yii branch. This solution allows for greater security (easier use of .htaccess, vpn and other advanced solutions).

In extreme cases, I could imagine debug data showing in the chrome developer toolbar or similar in firefox.

**Comment by samdark** [comment]
> It is not clear to me how the debug data from multiple applications (console, api, frontend ...) and its separated requests (eg for the current session) how will be listed.

For each server we're going to store "Data origin (application ID, server)". That would present in the list.

**Comment by kamarton** [comment]
> For each server we're going to store "Data origin (application ID, server)". That would present in the list.

Does this mean in multi-developer environments that I will not be able to list only session specific requests? This problem can even be a problem for a developer as it often requires them to search for bugs in different browsers at the same time.

**Comment by samdark** [comment]
No. That means that there will be tags and you'll be able filter data by these tags.

**Comment by kamarton** [comment]
> No. That means that there will be tags and you'll be able filter data by these tags.

This is totally good. Is it not clear that `Data origin (application ID, server)` is also a tag? If not then I do not understand why it should be differentiated.

**Comment by samdark** [comment]
It is a tag.

**Comment by mtangoo** [comment]
I just skimmed through comment so excuse me if it is discussed already. 
I propose that debug should be able to generate data without UI, like in case of API. But still the data format can be so easy that one can use external tool  (like IDE plugin) to analyze it without installing anything

**Comment by samdark** [comment]
Yes. That's planned.
